[default]

[corpus_files]
nouns = "resources/json_corpus/nouns_corpus.json"
adjectives = "resources/json_corpus/adjectives_corpus.json"
verbs = "resources/json_corpus/verbs_corpus.json"

[redis]

[telegram]
token = "YOUR_TOKEN"
welcome_message_file = "resources/welcome.md"
